### ISSUE TITLE
Importing anything from threlte/extras gives me error 

### ISSUE THREAD

**Issue by nicholasvperry** [threlte/threlte#395] opened 2023-05-18 15:40 UTC
I am trying to import from @threlte/extras and I get the following error:
Failed to load url three/examples/jsm/objects/GroundProjectedEnv (resolved id: three/examples/jsm/objects/GroundProjectedEnv). Does the file exist?

I am running my sveltekit app in vscode. I have fixed the vite.config
```
import { sveltekit } from '@sveltejs/kit/vite'
import type { UserConfig } from 'vite'

const config: UserConfig = {
	plugins: [sveltekit()],
	ssr: {
		noExternal: ['three', 'troika-three-text'],
	},
}

export default config
```

I have installed all the packages and have a very simple page
```
<script>
    import * as Extra from '@threlte/extras';
</script>
<h1>Welcome to SvelteKit</h1>
```

I have also tried importing what I need like this
```
<script>
   import {GLTF} from '@threlte/extras';
</script>
<h1>Welcome to SvelteKit</h1>
```

![image](https://github.com/threlte/threlte/assets/90103179/94cb9b77-d640-4330-8d1a-20743c4e3259)

**Comment by grischaerbe** [comment] 2023-05-18 19:34
Duplicate of #356

**Closed** 2023-05-18 19:35 UTC
